language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1
- ruby-head
- jruby-1.7.17
- jruby-head
script: bundle exec rake ci
notifications:
  slack:
    secure: IWfxqvq/zCJrt9bJyNfKQYWG034b/r675Ru4uoPf8entJ3q7dKugcK0MWJ0Skoe5KxOnY8EU2+07ZO8X5S72vwIIIuqkCyH4IrzTgsUMeirFdO9r98kfO636afkM9fosiJkI5Tm7GLWfNqNLwm/21Y3z9qU0uWcAZjGEwnc2DTg=
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
addons:
  code_climate:
    repo_token:
      secure: fNahzk7KsfGLJ8UnHLINuhF/DhGjhim87XC2j32DpDZVR1F+1MtwdDf8/nn2cEWfdp2LrGV4U0/4HtT9c7gg1i4TK4iqRItLElrRRcr7zhwBTzqAEhSEuEl3fgsSS7oR9G26719Zjrw3POaXtQk5kVgBv7yXa0WlYZtMNvyDQKA=
